# Site settings
title: blog.davep.org
email: davep@davep.org
description: Code, VR, stuff...
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://blog.davep.org"
github_username:  davep
plugins: [jekyll-paginate]
paginate: 5
paginate_path: /page:num/

# Build settings
markdown: kramdown

### _config.yml ends here
