# Site settings
title: blog.davep.org
email: davep@davep.org
description: Seems I'm toying with blogging again..
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://blog.davep.org"
twitter_username: davepdotorg
github_username:  davep

# Build settings
markdown: kramdown
